// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlbxD3vXck4jmHj0H08F_CMCRjV1XUhUM',
    appId: '1:20705805868:web:450a62a3755635d25b3389',
    messagingSenderId: '20705805868',
    projectId: 'grad-project-f90bd',
    authDomain: 'grad-project-f90bd.firebaseapp.com',
    storageBucket: 'grad-project-f90bd.appspot.com',
    measurementId: 'G-DB5D5F9V8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZsUQbQp0z8PPbx6Lb8UmuhOKzOfqA2E',
    appId: '1:20705805868:android:ad4c9cccff78a43c5b3389',
    messagingSenderId: '20705805868',
    projectId: 'grad-project-f90bd',
    storageBucket: 'grad-project-f90bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQBsVuL9AsNn32aH3kN6z79xvgti6taY',
    appId: '1:20705805868:ios:7b8a62569616dc965b3389',
    messagingSenderId: '20705805868',
    projectId: 'grad-project-f90bd',
    storageBucket: 'grad-project-f90bd.appspot.com',
    iosClientId: '20705805868-gp785f6978b2fatgee0run3ua53k49e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEQBsVuL9AsNn32aH3kN6z79xvgti6taY',
    appId: '1:20705805868:ios:7b8a62569616dc965b3389',
    messagingSenderId: '20705805868',
    projectId: 'grad-project-f90bd',
    storageBucket: 'grad-project-f90bd.appspot.com',
    iosClientId: '20705805868-gp785f6978b2fatgee0run3ua53k49e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientDoctor',
  );
}
